title: My website 
description: Super website
theme: just-the-docs

url: https://domantax.github.io/just-the-docs-template

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
